USE [hotel]

ALTER TABLE produtos DROP CONSTRAINT [servicoId]
ALTER TABLE produtos DROP CONSTRAINT [quartoProd]
ALTER TABLE dependentes DROP CONSTRAINT [dependenteId]
ALTER TABLE clientes DROP CONSTRAINT [quartoUser]

DROP TABLE IF EXISTS servicos
DROP TABLE IF EXISTS quartos
DROP TABLE IF EXISTS produtos
DROP TABLE IF EXISTS dependentes
DROP TABLE IF EXISTS clientes
